--- #YAML:1.0
name:               Net-Server-Mail
version:            0.20
abstract:           Class to easily create a mail server
author:
    - Xavier Guimard <x.guimard@free.fr>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::Most:  0
requires:
    IO::Socket::SSL:  1.831
    Net::SMTP:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
recommends:
    IO::Socket::SSL:  1.831
